window.languages = [
  ['zh-Hans', '简体中文', {
    'opt-title': '选项',
    'opt-sfx': '播放音效',
    'opt-dark': '深色主题',
    'opt-high-con': '清晰显示',
    'opt-nota': '音符记号',
    'opt-nota-num': '数字',
    'opt-nota-solf': '唱名',
    'opt-nota-roman': '罗马',
    'opt-nota-aikin': '图形',
    'opt-lang': '界面语言',
    'opt-source': '程序源码',
    'opt-dist': '依照木兰公共许可证分发',
  }],
  ['en', 'English', {
    'opt-title': 'Options',
    'opt-sfx': 'Sound effects',
    'opt-dark': 'Dark theme',
    'opt-high-con': 'Clear display',
    'opt-nota': 'Notation',
    'opt-nota-num': 'Numeral',
    'opt-nota-solf': 'Solfege',
    'opt-nota-roman': 'Roman',
    'opt-nota-aikin': 'Shape',
    'opt-lang': 'Language',
    'opt-source': 'Program source',
    'opt-dist': ' distributed under the Mulan Public License',
  }],
];
